# Makefile for managing Python project tasks
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

venv: ## Create Python virtual environment with CUDA 12.4 and dependencies
	bash scripts/build_venv.sh

container: ## Build and run Docker container with GPU support
	bash scripts/build_container.sh

clean-venv: ## Remove Python virtual environment
	rm -rf venv

clean-container: ## Remove Docker container
	docker rm -f alzheimer-mri-container 2>/dev/null || true